version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Use Python 3.12
    commands:
      - echo Installing dependencies...
      - python --version  # Verify Python version
      - pip install --no-cache-dir -r requirements.txt

  build:
    commands:
      - echo Build phase...
      - python app.py  # Replace with your actual build/test command

artifacts:
  files:
    - imagedefinitions.json
