version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Upgrading pip...
      - pip install --upgrade pip
      - echo Installing dependencies...
      - pip install --no-cache-dir -r requirements.txt
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-image .
      - echo '[{"name":"my-container","imageUri":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/my-repo:'$CODEBUILD_RESOLVED_SOURCE_VERSION'"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
