version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Using Python as the runtime version
    commands:
      - echo Installing Docker...
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sudo sh get-docker.sh
      - sudo usermod -aG docker $USER
      - docker --version  # Verify Docker installation
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-image .
      - echo '[{"name":"my-container","imageUri":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/my-repo:'$CODEBUILD_RESOLVED_SOURCE_VERSION'"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

